name: Flutter CI/CD

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK (school3)
        run: flutter build apk --release --flavor school3 --target lib/main.dart

      - name: Build Release AAB (school3)
        run: flutter build appbundle --flavor school3 --target lib/main.dart

      - name: Upload APK Artifact
        uses: actions/upload-artifact@9a08c3e1598dc46d17e9d8311e3c91f96c48f1ac
        with:
          name: school3-release-apk
          path: build/app/outputs/flutter-apk/app-school3-release.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@9a08c3e1598dc46d17e9d8311e3c91f96c48f1ac
        with:
          name: school3-release-aab
          path: build/app/outputs/bundle/school3Release/app-school3-release.aab
