name: Flutter CI/CD
env:
  FLUTTER_VERSION: "3.2.3"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Get Packages
        run: flutter pub get


      - name: Build Release School3 APK
        run: flutter build apk --release --flavor school3 --target lib/main.dart


      - name: Build School3 appbundle
        run: flutter build appbundle --flavor school3 --target lib/main.dart


      - name: Upload School3 APK
        uses: actions/upload-artifact@v3
        with:
          name: school3-release-apk
          path: build/app/outputs/flutter-apk/app-school3-release.apk

      
      - name: Upload School3 AAB
        uses: actions/upload-artifact@v3
        with:
          name: school3-release-apk
          path: build/app/outputs/bundle/school3Release/app-school3-release.aab
