name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter_build:
    name: Build APK & AAB (School3)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'  # Use your installed Flutter version
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore and Save it
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.jks
          echo "KEYSTORE_PATH=$PWD/release-key.jks" >> $GITHUB_ENV

      - name: Set up Android Keystore Credentials
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV

      - name: Build APK (School3)
        run: flutter build apk --release --flavor school3 --target lib/main.dart
        env:
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # - name: Build AAB (School3)
      #   run: flutter build appbundle --flavor school3 --target lib/main.dart
      #   env:
      #     KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
      #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload School3 APK
        uses: actions/upload-artifact@v4
        with:
          name: school3-release-apk
          path: build/app/outputs/flutter-apk/app-school3-release.apk

      # - name: Upload School3 AAB
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: school3-release-aab
      #     path: build/app/outputs/bundle/school3Release/app-school3-release.aab
